---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: universal-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: universal-operator
  template:
    metadata:
      labels:
        name: universal-operator
    spec:
      serviceAccountName: universal-operator
      containers:
        - name: universal-operator
          image: "quay.io/saberkan/universal-operator:v0.0.1"
          resources:
            requests:
              cpu: '1'
              memory: 500Mi
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "universal-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6789
            initialDelaySeconds: 5
            periodSeconds: 3
      volumes:
        - name: runner
          emptyDir: {}
